theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-start
  home:
    head:
      title: site
  logo:
    header: "/assets/images/logo-header.svg"
    footer: "/assets/images/logo-footer.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  posts:
    index:
      layout: grid
      options:
        categories: false
  events:
    index:
      options:
        categories: false
  search:
    active: true
    positions:
      - primary
      - taxonomies #custom
